### PR TITLE
Revert "Revert "Updates gradle plugin""

### PR DESCRIPTION
**Pull request by agilob**
Reverts openbmap/android#162 :D
Keep it this way

### CODE REVIEW

**Comment by wish7code** [comment]
Fine :D

**Comment by agilob** [comment]
EH, you merged it again. Please test it now with me. If you could fix the issue with server it would help, it's not possible to upload saved sessions now.

**Comment by wish7code** [comment]
My misunderstanding, sorry.. Thought it was ready to merge after review.

I'll have a look at the server side and come back..

**Comment by wish7code** [comment]
Could you verify? I just tested anonymous upload, which seems to work..

**Comment by agilob** [comment]
I can't upload session as logged user since beginning of May, since service become unavailable. I think #154 is related.

**Pull request merged**
