### PR TITLE
General cleanup of unused resources and printStacktraces

### PR DESCRIPTION
**Pull request by agilob**
```
➜  android git:(master) gradle dependencyUpdate
Incremental java compilation is an incubating feature.
:dependencyUpdates

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.jjoe64:graphview:4.0.1
 - com.neenbedankt.gradle.plugins:android-apt:1.8
 - junit:junit:4.12
 - org.apache.commons:commons-lang3:3.4
 - org.greenrobot:eventbus:3.0.0
 - org.greenrobot:eventbus-annotation-processor:3.0.1

The following dependencies have later milestone versions:
 - com.android.support:appcompat-v7 [23.2.1 -> 24.0.0-beta1]
 - com.android.support:support-v13 [23.2.1 -> 24.0.0-beta1]
 - com.android.support:support-v4 [23.2.1 -> 24.0.0-beta1]
 - com.android.tools.build:gradle [2.1.0 -> 2.2.0-alpha2]
 - com.caverock:androidsvg [1.2.1 -> 1.2.2-beta-1]
 - com.github.ben-manes:gradle-versions-plugin [0.11.3 -> 0.12.0]
 - cz.msebera.android:httpclient [4.4.1.1 -> 4.4.1.2]
 - org.apache.httpcomponents:httpmime [4.2.3 -> 4.5.2]
 - org.mapsforge:mapsforge [0.6.0 -> 0.6.1-rc2]
 - org.mapsforge:mapsforge-core [0.6.0 -> 0.6.1-rc2]
 - org.mapsforge:mapsforge-map [0.6.0 -> 0.6.1-rc2]
 - org.mapsforge:mapsforge-map-android [0.6.0 -> 0.6.1-rc2]
 - org.mapsforge:mapsforge-map-reader [0.6.0 -> 0.6.1-rc2]

Generated report file build/dependencyUpdates/report.txt

BUILD SUCCESSFUL

Total time: 29.901 secs
```

You should always use logger to log exceptions. printstacktrace always generates and bufferes stacktrace, but it's never printed in android so it's a huge was of resources.

Some exceptions don't provide message so getMessage will fail with NullPointerException, so prefer use of toString :)

### CODE REVIEW

**Comment by wish7code** [comment]
@agilob Thanks a lot man!

Automatic merge failed as I had some conflicts..
I'm closing this, changes are in fa03042b

**Comment by agilob** [comment]
Yup, I expected the merge conflict. Thanks for merging. I'll be working more on this project in the next couple of weeks.

**Comment by agilob** [comment]
Not all changes went there...

**Comment by wish7code** [comment]
Any hints, how I could validate, e.g. gerenerate a report to compare which changes are missing?

I'm not too experienced with git, so I tried to merge manually and thereby probably missed something..

**Comment by agilob** [comment]
Hmm the easiest would be like:
1. `git remote add agilob git@github.com:agilob/android.git` which adds my repo to your list of remote repositories on your local repo. do it in your git folder. You do it only once.
2. After I make PR and it's ready to merge (no WIP in title) you need to refresh list of my branches, `git pull agilob <branchname>`
3. If you want to test my changes do `git checkout agilob/<branchname>`
4. If you want to merge the branch just do `git merge --no-ff agilob/<branchname>` (`git checkout origin/master` before to go back to your branch). --no-ff option will always generate merge commit.
4.1 If you have merge conflicts, you should let me know, and I should solve them
5. It's a good practice and it's supported by GitHub now to sign your merge commits when working in organisation. To do it: https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work There are various points for and against it, but when we work in rolling-release system, top of master and merge commits should be signed to let users know the thing was verified by you personally.

What we do here is git flow, you can [read more about it here](https://www.atlassian.com/pt/git/workflows) :)

**Pull request closed without merging**
